apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: registry
    app.kubernetes.io/name: registry
  name: registry
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/component: registry
        app.kubernetes.io/name: registry
    spec:
      containers:
      - name: registry
        image: registry:2.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/registry
        - serve
        - /etc/docker/registry/config.yml
        ports:
        - name: http
          containerPort: 5000
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 40Mi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
        volumeMounts:
        - name: registry-vol
          mountPath: /var/lib/registry
          # subPath: data
      volumes:
      - name: registry-vol
        persistentVolumeClaim:
          claimName: registry-pvc
