apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: registry
    app.kubernetes.io/name: registry
  name: registry
  namespace: default
spec:
  selector:
    app.kubernetes.io/component: registry
    app.kubernetes.io/name: registry
  ports:
  - name: http
    port: 5000
    targetPort: http
  type: NodePort
