apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: python-app
    app.kubernetes.io/name: python-app
  name: python-app
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: python-app
      app.kubernetes.io/name: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: python-app
        app.kubernetes.io/name: python-app
    spec:
      containers:
      - name: python-app
        image:  kemplerart/vex-svc:latest-test-python
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        resources:
          requests:
            memory: 2Gi
            cpu: 1500m
          limits:
            memory: 4Gi
            cpu: 2000m
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
