apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: python-app
    app.kubernetes.io/name: python-app
  name: python-app
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/component: python-app
    app.kubernetes.io/name: python-app
  type: ClusterIP
